### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by marksev1** [mmornati/kerberosio-hooks#10]
Can you please explain more how this works? Does it trigger when motion is detected and send a http post to some server of my choice with information in json format?
This email plugin does it work, can it send to gmail? Can you make it so that it sends only emails from a specific camera (inside the house, if I had more) and only in a specific time (lets say during the night or something like that).
What about if I have multiple kerberosio instances (multiple cameras)?

**Comment by mmornati** [comment]
Sorry... didn't saw your message before.
The project is not installed on the kerberosIO server. It's an external service configurable as you wish (mail, pushbullet or whatever) and inside your kerberosio installation you have just to set it into the notification part (as external server).
The plugin email is working, I'm using right now and the mail are sent to gmail... but I'm using a different SMTP server (to deliver the mails) as the GMail one with the 2 factor authentication is not working.

A message is sent when a motion is detected with the screenshot of your room (example here: https://blog.mornati.net/pushbullet-notifications-for-kerberos-io/).

If you have several Kerberos IO you can configure all of them with the same deliver server.

Sorry again for the delay in the response

**Comment by marksev1** [comment]
No problem. Cool stuff, first I need to buy hardware and install kerberosio, then I'm gonna maybe ask you for instructions for setting this up.

**Comment by mmornati** [comment]
No problem.

I will prepare documentation on github for you... You questions made me
thinking that it was not so clear how to use it.

Thanks
