### ISSUE TITLE
Error when running index.js

### ISSUE THREAD

**Issue by kwright5150** [mmornati/kerberosio-hooks#23]
Hello I am getting an error that says

"class PushBulletConfig extends AbstractConfiguration {
^^^^^
SyntaxError: Unexpected reserved word.

**Comment by mmornati** [comment]
What is the version of NodeJS are you using?

**Comment by kwright5150** [comment]
Whatever version was installed by default on Raspberry Pi Pixel. What
version do I need?

**Comment by mmornati** [comment]
No idea what version is on Pixel.
To know it you can simply execute:
`node -v`

I tested it on node v4.0.0 but I suggest you to use the latest lts (long time support).

To install it the best way is using the Node Version Manager (nvm) https://github.com/creationix/nvm#install-script which is allowing you to skip the usage of the default RPi or whatever repositories.
Try executing:
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
nvm install --lts`

And then execute again the index.js

**Comment by kwright5150** [comment]
Alright I'm up and running now! However on the output of the terminal it says this:

{ Error: ENOENT: no such file or directory, stat './etc/opt/kerberosio/capture/1493046251_6-697549_frontdoor_22-25-789-635_113630_333.jpg'
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: './test/1493046251_6-697549_frontdoor_22-25-789-635_113630_333.jpg' }
{ Error: connect ECONNREFUSED 127.0.0.1:8010
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
  code: 'ECONNECTION',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8010,
  command: 'CONN' }

**Comment by kwright5150** [comment]
The server is running now! However my image does not get sent to PushBullet. 

{ Error: ENOENT: no such file or directory, stat './test/1493046251_6-697549_frontdoor_22-25-789-635_113630_333.jpg'

I know that is not where the images reside and I have changed the directory with the same results.

**Comment by kwright5150** [comment]
Thank you, that fixed it!
